# AI PROJECT
## Training AI car to race in TORCS using neural networks


## Group Members:

In [2]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [26]:
#Load the dataset
df = pd.read_csv('data.csv')
df.head()

Angle   CurrentLapTime   Damage   DistanceFromStart   DistanceCovered  \
0    0.0           -0.982      0.0             6201.46               0.0   
1    0.0           -0.962      0.0             6201.46               0.0   
2    0.0           -0.942      0.0             6201.46               0.0   
3    0.0           -0.922      0.0             6201.46               0.0   
4    0.0           -0.902      0.0             6201.46               0.0   

    FuelLevel   Gear   LastLapTime   Opponent_1  Opponent_2  ...  \
0     94.0000      0           0.0      16.9999       200.0  ...   
1     94.0000      0           0.0      16.9999       200.0  ...   
2     93.9999      0           0.0      16.9999       200.0  ...   
3     93.9998      0           0.0      16.9999       200.0  ...   
4     93.9997      0           0.0      16.9999       200.0  ...   

    WheelSpinVelocity_1  WheelSpinVelocity_2  WheelSpinVelocity_3  \
0                   0.0                  0.0                  0.0   
1                   0.0                  0.0                  0.0   
2                   0.0                  0.0                  0.0   
3                   0.0                  0.0                  0.0   
4                   0.0                  0.0                  0.0   

   WheelSpinVelocity_4         Z   Acceleration  Braking  Clutch  Gear  \
0                  0.0  0.345263            1.0      0.0    0.64     1   
1                  0.0  0.345263            1.0      0.0    0.64     1   
2                  0.0  0.345263            1.0      0.0    0.64     1   
3                  0.0  0.345263            1.0      0.0    0.64     1   
4                  0.0  0.345263            1.0      0.0    0.64     1   

   Steering  
0 -0.028559  
1 -0.028559  
2 -0.028559  
3 -0.028559  
4 -0.028559  

[5 rows x 79 columns]

In [27]:
# Strip trailing spaces from column names
df.columns = [col.strip() for col in df.columns]
df.columns.tolist()

['Angle',
 'CurrentLapTime',
 'Damage',
 'DistanceFromStart',
 'DistanceCovered',
 'FuelLevel',
 'Gear',
 'LastLapTime',
 'Opponent_1',
 'Opponent_2',
 'Opponent_3',
 'Opponent_4',
 'Opponent_5',
 'Opponent_6',
 'Opponent_7',
 'Opponent_8',
 'Opponent_9',
 'Opponent_10',
 'Opponent_11',
 'Opponent_12',
 'Opponent_13',
 'Opponent_14',
 'Opponent_15',
 'Opponent_16',
 'Opponent_17',
 'Opponent_18',
 'Opponent_19',
 'Opponent_20',
 'Opponent_21',
 'Opponent_22',
 'Opponent_23',
 'Opponent_24',
 'Opponent_25',
 'Opponent_26',
 'Opponent_27',
 'Opponent_28',
 'Opponent_29',
 'Opponent_30',
 'Opponent_31',
 'Opponent_32',
 'Opponent_33',
 'Opponent_34',
 'Opponent_35',
 'Opponent_36',
 'RacePosition',
 'RPM',
 'SpeedX',
 'SpeedY',
 'SpeedZ',
 'Track_1',
 'Track_2',
 'Track_3',
 'Track_4',
 'Track_5',
 'Track_6',
 'Track_7',
 'Track_8',
 'Track_9',
 'Track_10',
 'Track_11',
 'Track_12',
 'Track_13',
 'Track_14',
 'Track_15',
 'Track_16',
 'Track_17',
 'Track_18',
 'Track_19',
 'TrackPosition'

In [28]:
#Shape of DataFrame
df.shape

(15562, 79)

In [29]:
X = df.drop(columns=['Acceleration', 'Braking','Clutch', 'Gear', 'Steering'])
y = df[['Acceleration', 'Braking','Clutch', 'Gear', 'Steering']]
X.head(), y.head()

(   Angle  CurrentLapTime  Damage  DistanceFromStart  DistanceCovered  \
 0    0.0          -0.982     0.0            6201.46              0.0   
 1    0.0          -0.962     0.0            6201.46              0.0   
 2    0.0          -0.942     0.0            6201.46              0.0   
 3    0.0          -0.922     0.0            6201.46              0.0   
 4    0.0          -0.902     0.0            6201.46              0.0   
 
    FuelLevel  LastLapTime  Opponent_1  Opponent_2  Opponent_3  ...  Track_16  \
 0    94.0000          0.0     16.9999       200.0       200.0  ...   13.9476   
 1    94.0000          0.0     16.9999       200.0       200.0  ...   13.9476   
 2    93.9999          0.0     16.9999       200.0       200.0  ...   13.9476   
 3    93.9998          0.0     16.9999       200.0       200.0  ...   13.9476   
 4    93.9997          0.0     16.9999       200.0       200.0  ...   13.9476   
 
    Track_17  Track_18  Track_19  TrackPosition  WheelSpinVelocity_1  \


In [30]:
y.shape

(15562, 6)

In [31]:
#Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled  

array([[ 0.01192514, -1.45207052,  0.        , ..., -2.76754534,
        -2.77316717,  1.36952412],
       [ 0.01192514, -1.45147768,  0.        , ..., -2.76754534,
        -2.77316717,  1.36952412],
       [ 0.01192514, -1.45088484,  0.        , ..., -2.76754534,
        -2.77316717,  1.36952412],
       ...,
       [-0.99665227, -0.1154524 ,  0.        , ..., -1.25805059,
        -1.2753706 ,  1.04716883],
       [-0.98130294, -0.11485956,  0.        , ..., -1.25824029,
        -1.27550957,  1.01719372],
       [-0.96574516, -0.11426672,  0.        , ..., -1.25845736,
        -1.2756505 ,  0.98967559]])

In [37]:
#Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((12449, 73), (3113, 73), (12449, 6), (3113, 6))

In [38]:
# Ytest is datafram so convert to array
y_test = y_test.values
print(y_test.shape)
print(y_test[0:5])



(3113, 6)
[[ 1.          0.          0.63999999  1.          1.         -0.02174521]
 [ 0.          0.          0.          3.          3.         -0.06947872]
 [ 0.82083607  0.          0.          2.          2.          0.33756357]
 [ 1.          0.          0.          4.          4.         -0.02545111]
 [ 0.99562663  0.          0.          3.          3.          0.08160117]]


In [39]:
#Drop first column of y_test
y_test = np.delete(y_test, 3, axis=1)
print(y_test.shape)
print(y_test[0:5])


(3113, 5)
[[ 1.          0.          0.63999999  1.         -0.02174521]
 [ 0.          0.          0.          3.         -0.06947872]
 [ 0.82083607  0.          0.          2.          0.33756357]
 [ 1.          0.          0.          4.         -0.02545111]
 [ 0.99562663  0.          0.          3.          0.08160117]]


In [40]:
y_train = np.delete(y_train, 3, axis=1)
print(y_train.shape)
print(y_train[0:5])

(12449, 5)
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  5.00000000e+00
   5.17299595e-05]
 [ 9.99999821e-01  0.00000000e+00  0.00000000e+00  5.00000000e+00
  -1.25332847e-02]
 [ 0.00000000e+00  8.68257344e-01  0.00000000e+00  3.00000000e+00
  -9.16183367e-02]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00  2.00000000e+00
   1.96708441e-02]
 [ 0.00000000e+00  2.54323661e-01  0.00000000e+00  5.00000000e+00
   9.71237756e-03]]


In [13]:
# Check X_train:
print(X_train[0:5])
print(X_train.shape)


[[ 0.0080785   2.06620052  0.          2.14503508  0.89314483 -1.10898848
  -0.62228133 -1.67054411  0.30298133  0.27459961  0.23531528  0.14139417
   0.12458456  0.10515415  0.10407631  0.10277568  0.09445251  0.09469325
   0.10318154  0.10939301  0.11972723  0.10468252  0.0768131   0.08084802
   0.          0.08885934  0.06167091  0.03929737  0.03106017  0.02535689
   0.02295133  0.03287994  0.04389672  0.09434418  0.1490513   0.16631732
   0.14673462  0.18605354  0.216924    0.24960478  0.33129227  0.35439739
   0.48574718 -0.13161937  1.30443718  1.67099816 -0.04324041 -0.01550898
   0.05070007  0.05090506  0.06773571  0.08507875  0.03474115  0.04691228
   0.03687784  0.10186026  2.02312441  2.15051405  2.23401449  0.03353485
  -0.26046442 -0.11345276 -0.08399628 -0.03559613 -0.05374064 -0.06211127
  -0.06146586 -0.05650064  1.68967406  1.68671414  1.67250862  1.66382864
  -1.98809774]
 [ 0.62140396  0.73456226  0.          0.63252639 -0.21443894  0.10455547
  -0.62228133  0.467028

In [41]:
model = Sequential()
model.add(Dense(64, input_dim=73, activation='relu'))
model.add(Dense(64, activation='relu'))
#Output layer with 5 neurons for 5 outputs
model.add(Dense(5, activation='linear'))

model.compile(optimizer=Adam(learning_rate=0.001), loss='mean_squared_error', metrics=['mae'])


c:\Users\Pc\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [42]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │         4,736 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 5)              │           325 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,221 (36.02 KB)

 Trainable params: 9,221 (36.02 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/100


312/312 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.7158 - mae: 0.4461 - val_loss: 0.0510 - val_mae: 0.1457
Epoch 2/100
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0392 - mae: 0.1276 - val_loss: 0.0263 - val_mae: 0.1004
Epoch 3/100
312/312 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0234 - mae: 0.0950 - val_loss: 0.0197 - val_mae: 0.0837
Epoch 4/100
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0176 - mae: 0.0805 - val_loss: 0.0166 - val_mae: 0.0744
Epoch 5/100
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0157 - mae: 0.0727 - val_loss: 0.0148 - val_mae: 0.0724
Epoch 6/100
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0160 - mae: 0.0724 - val_loss: 0.0135 - val_mae: 0.0657
Epoch 7/100
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0115 - mae: 0.0608 - val_loss: 0.0132 - val_mae: 0.0636
Epoch 8/100
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0110 - mae: 0.0585 - val_loss: 0.0119 - val_mae: 0.0595
Epoch 9/100
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss:

In [ ]:
# Example single sample for prediction
sample_data = [[-1.00787E-4,34.206,0.0,1545.23,1549.23,92.8378,4,0.0,200.0,200.0,200.0,196.511,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,1,8289.75,192.203,-6.49205,3.53352,3.17882,3.29412,4.19034,5.70653,10.5383,16.633,79.7683,62.3312,50.9192,48.4277,46.0765,37.9989,30.4697,25.0886,21.1987,14.4222,11.2478,9.10999,8.82118,0.470197,162.039,159.93,167.623,167.314]]

# Convert to numpy array
sample_data = np.array(sample_data)

# Apply the same scaler that was used for training data
scaled_sample = scaler.transform(sample_data)

# Make prediction
prediction = model.predict(scaled_sample)
print(prediction.flatten())

# Print the predicted outputs
print("Predicted outputs:")
print("Acceleration:", prediction[0][0])
print("Braking:", prediction[0][1])
print("Clutch:", prediction[0][2])
print("Gear:", prediction[0][3])
print("Steering:", prediction[0][4])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[-148.41876   -37.56597  2197.0686   2635.457     -33.483864]
Predicted outputs:
Braking: -148.41876
Clutch: -37.56597
Gear: 2197.0686
Steering: 2635.457
Acceleration: -33.483864


c:\Users\Pc\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [44]:
prediction = model.predict(X_test[0].reshape(1, -1))
print("Predicted outputs for test data:")
print("Acceleration:", prediction[0][0])
print("Braking:", prediction[0][1])
print("Clutch:", prediction[0][2])
print("Gear:", prediction[0][3])
print("Steering:", prediction[0][4])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
Predicted outputs for test data:
Acceleration: 0.93807304
Braking: 0.02528542
Clutch: 0.66060776
Gear: 1.1113911
Steering: -0.021719463


In [22]:
len(sample_data[0])

73