# AI PROJECT
## Training AI car to race in TORCS using neural networks


## Group Members:

In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#Load the dataset
df = pd.read_csv('combined_data.csv')
df.head()

Angle   CurrentLapTime   Damage   DistanceFromStart   DistanceCovered  \
0    0.0           -0.982      0.0             6201.46               0.0   
1    0.0           -0.962      0.0             6201.46               0.0   
2    0.0           -0.942      0.0             6201.46               0.0   
3    0.0           -0.922      0.0             6201.46               0.0   
4    0.0           -0.902      0.0             6201.46               0.0   

    FuelLevel   Gear   LastLapTime   Opponent_1  Opponent_2  ...  \
0     94.0000      0           0.0      16.9999       200.0  ...   
1     94.0000      0           0.0      16.9999       200.0  ...   
2     93.9999      0           0.0      16.9999       200.0  ...   
3     93.9998      0           0.0      16.9999       200.0  ...   
4     93.9997      0           0.0      16.9999       200.0  ...   

    WheelSpinVelocity_1  WheelSpinVelocity_2  WheelSpinVelocity_3  \
0                   0.0                  0.0                  0.0   
1                   0.0                  0.0                  0.0   
2                   0.0                  0.0                  0.0   
3                   0.0                  0.0                  0.0   
4                   0.0                  0.0                  0.0   

   WheelSpinVelocity_4         Z   Acceleration  Braking  Clutch  Gear  \
0                  0.0  0.345263            1.0      0.0    0.64     1   
1                  0.0  0.345263            1.0      0.0    0.64     1   
2                  0.0  0.345263            1.0      0.0    0.64     1   
3                  0.0  0.345263            1.0      0.0    0.64     1   
4                  0.0  0.345263            1.0      0.0    0.64     1   

   Steering  
0 -0.028559  
1 -0.028559  
2 -0.028559  
3 -0.028559  
4 -0.028559  

[5 rows x 79 columns]

In [3]:
# Strip trailing spaces from column names
df.columns = [col.strip() for col in df.columns]
df.columns.tolist()

['Angle',
 'CurrentLapTime',
 'Damage',
 'DistanceFromStart',
 'DistanceCovered',
 'FuelLevel',
 'Gear',
 'LastLapTime',
 'Opponent_1',
 'Opponent_2',
 'Opponent_3',
 'Opponent_4',
 'Opponent_5',
 'Opponent_6',
 'Opponent_7',
 'Opponent_8',
 'Opponent_9',
 'Opponent_10',
 'Opponent_11',
 'Opponent_12',
 'Opponent_13',
 'Opponent_14',
 'Opponent_15',
 'Opponent_16',
 'Opponent_17',
 'Opponent_18',
 'Opponent_19',
 'Opponent_20',
 'Opponent_21',
 'Opponent_22',
 'Opponent_23',
 'Opponent_24',
 'Opponent_25',
 'Opponent_26',
 'Opponent_27',
 'Opponent_28',
 'Opponent_29',
 'Opponent_30',
 'Opponent_31',
 'Opponent_32',
 'Opponent_33',
 'Opponent_34',
 'Opponent_35',
 'Opponent_36',
 'RacePosition',
 'RPM',
 'SpeedX',
 'SpeedY',
 'SpeedZ',
 'Track_1',
 'Track_2',
 'Track_3',
 'Track_4',
 'Track_5',
 'Track_6',
 'Track_7',
 'Track_8',
 'Track_9',
 'Track_10',
 'Track_11',
 'Track_12',
 'Track_13',
 'Track_14',
 'Track_15',
 'Track_16',
 'Track_17',
 'Track_18',
 'Track_19',
 'TrackPosition'

In [4]:
#Shape of DataFrame
df.shape

(176437, 79)

In [ ]:

df.head()

Angle  CurrentLapTime  Damage  DistanceFromStart  DistanceCovered  \
0  0.038905          36.206     3.0            1105.29      1220.250000   
1 -0.043363          73.600  4391.0            1127.72      3003.650000   
2  0.034884          75.074     0.0            1172.78      1287.770000   
3  0.001033           0.280     0.0            6201.81         0.351074   
4 -0.027877           6.230     0.0            4162.37        68.999000   

   FuelLevel  Gear  LastLapTime  Opponent_1  Opponent_2  ...  \
0    54.5903     4        0.000       200.0       200.0  ...   
1    56.0194     3      125.706       200.0       200.0  ...   
2    49.9267     1        0.000       200.0       200.0  ...   
3    93.9729     1        0.000       200.0       200.0  ...   
4    49.9446     2        0.000       200.0       200.0  ...   

   WheelSpinVelocity_1  WheelSpinVelocity_2  WheelSpinVelocity_3  \
0            121.45400            120.79500            121.47200   
1             88.37010             88.39190             88.67770   
2             69.67710             69.27890             69.67940   
3              7.90839              7.91359              9.80411   
4             69.41360             69.30790             65.30790   

   WheelSpinVelocity_4         Z  Acceleration  Braking  Clutch  Gear  \
0            120.85200  0.321642      0.341759      0.0   0.000     4   
1             88.09270  0.344850      0.000000      0.0   0.000     3   
2             69.28560  0.474639      1.000000      0.0   0.475     1   
3              9.07698  0.345635      1.000000      0.0   0.640     1   
4             65.38390  0.474598      1.000000      0.0   0.000     2   

   Steering  
0  0.008182  
1 -0.224291  
2  0.034809  
3 -0.028148  
4 -0.019737  

[5 rows x 79 columns]

In [5]:
X = df.drop(columns=['Acceleration', 'Braking','Clutch', 'Gear', 'Steering'])
y = df[['Acceleration', 'Braking','Clutch', 'Steering']]
X.head(), y.head()

(   Angle  CurrentLapTime  Damage  DistanceFromStart  DistanceCovered  \
 0    0.0          -0.982     0.0            6201.46              0.0   
 1    0.0          -0.962     0.0            6201.46              0.0   
 2    0.0          -0.942     0.0            6201.46              0.0   
 3    0.0          -0.922     0.0            6201.46              0.0   
 4    0.0          -0.902     0.0            6201.46              0.0   
 
    FuelLevel  LastLapTime  Opponent_1  Opponent_2  Opponent_3  ...  Track_16  \
 0    94.0000          0.0     16.9999       200.0       200.0  ...   13.9476   
 1    94.0000          0.0     16.9999       200.0       200.0  ...   13.9476   
 2    93.9999          0.0     16.9999       200.0       200.0  ...   13.9476   
 3    93.9998          0.0     16.9999       200.0       200.0  ...   13.9476   
 4    93.9997          0.0     16.9999       200.0       200.0  ...   13.9476   
 
    Track_17  Track_18  Track_19  TrackPosition  WheelSpinVelocity_1  \


In [6]:
y.shape

(176437, 4)

In [7]:
#Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled  

array([[-0.05706978, -1.30079194, -0.86052732, ..., -1.72669027,
        -1.72723789, -0.66799698],
       [-0.05706978, -1.3002641 , -0.86052732, ..., -1.72669027,
        -1.72723789, -0.66799698],
       [-0.05706978, -1.29973627, -0.86052732, ..., -1.72669027,
        -1.72723789, -0.66799698],
       ...,
       [-0.03102186,  0.76559071, -0.85920578, ...,  0.98542726,
         0.98485141, -0.85497871],
       [-0.03100488,  0.76611854, -0.85920578, ...,  0.98553849,
         0.98320581, -0.85678956],
       [-0.03102186,  0.76664638, -0.85920578, ...,  0.98682879,
         0.98494036, -0.85497097]])

In [8]:
#Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((141149, 73), (35288, 73), (141149, 4), (35288, 4))

In [9]:
# Ytest is datafram so convert to array
y_test = y_test.values
print(y_test.shape)
print(y_test[0:5])


(35288, 4)
[[ 1.33041770e-03  0.00000000e+00  4.74999994e-01 -7.60235712e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.57791744e-02]
 [ 1.00000000e+00  0.00000000e+00  4.74999994e-01  6.30383438e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.83448792e-02]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00  2.44415686e-01]]


In [ ]:
#Drop 4th column of y_test
# y_test = np.delete(y_test, 3, axis=1)
# print(y_test.shape)
# print(y_test[0:5])


In [ ]:
# y_train = np.delete(y_train, 3, axis=1)
# print(y_train.shape)
# print(y_train[0:5])

In [10]:
# Check X_train:
print(X_train[0:5])
print(X_train.shape)


[[-6.42613472e-02  1.24006485e+00 -8.60527324e-01  2.12521226e+00
   6.27126048e-01  2.17907905e+00 -7.47318180e-01  3.07024616e-01
   2.43482261e-01  2.22043998e-01 -3.05538603e+00  1.88709309e-01
   1.88346063e-01  1.90079032e-01  1.91869364e-01  1.77798093e-01
   1.82558963e-01  1.85880941e-01  1.93584994e-01  2.01260128e-01
   2.15439006e-01  2.40782543e-01  2.76913187e-01  2.76730765e-01
   5.01599323e-01  5.10772971e-01  2.21038372e-01  2.01451583e-01
   1.70278833e-01  1.59082392e-01  1.48145920e-01  1.40273600e-01
   1.57076070e-01  1.52929082e-01  1.53747211e-01  1.52462131e-01
   1.54361048e-01  1.80467933e-01  1.96740027e-01  1.92806191e-01
   2.29863338e-01  2.64481830e-01 -1.36753158e+00 -2.43758666e+00
   2.04049262e+00  3.29812923e+00 -5.60278161e-02  9.39463585e-02
   2.49091449e-03 -1.78736917e-02 -4.05482380e-02 -6.87274847e-02
  -5.53781703e-02 -2.13344690e-02 -3.93804485e-02  6.20705697e-02
   1.58156664e+00  1.56199128e+00  1.47447999e+00  3.58451108e-01
   1.42017

In [11]:
model = Sequential()
model.add(Dense(512, input_dim=73, activation='relu',kernel_initializer='he_normal'))
model.add(Dense(128, activation='relu',kernel_initializer='he_normal'))
model.add(Dense(64, activation='relu',kernel_initializer='he_normal'))
model.add(Dropout(0.2))  # Dropout layer to prevent overfitting
model.add(Dense(32, activation='relu',kernel_initializer='he_normal'))
#Output layer with 3 neurons for 3 outputs
model.add(Dense(4, activation='linear',kernel_initializer='he_normal'))

model.compile(optimizer=Adam(learning_rate=0.007), loss='mean_squared_error', metrics=['mae'])


c:\Users\Zestro\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 512)            │        37,888 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │        65,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 4)              │           132 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 114,020 (445.39 KB)

 Trainable params: 114,020 (445.39 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
#Use EarlyStopping to prevent overfitting
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)


In [14]:
model.fit(X_train, y_train,validation_data=(X_test,y_test), epochs=100, batch_size=256, verbose=1,callbacks=[early_stopping])

Epoch 1/100
552/552 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.2880 - mae: 0.2189 - val_loss: 0.0276 - val_mae: 0.1022
Epoch 2/100
552/552 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0244 - mae: 0.0853 - val_loss: 0.0260 - val_mae: 0.0976
Epoch 3/100
552/552 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0197 - mae: 0.0725 - val_loss: 0.0194 - val_mae: 0.0800
Epoch 4/100
552/552 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0178 - mae: 0.0670 - val_loss: 0.0209 - val_mae: 0.0884
Epoch 5/100
552/552 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0166 - mae: 0.0638 - val_loss: 0.0174 - val_mae: 0.0749
Epoch 6/100
552/552 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0156 - mae: 0.0614 - val_loss: 0.0172 - val_mae: 0.0753
Epoch 7/100
552/552 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0147 - mae: 0.0586 - val_loss: 0.0175 - val_mae: 0.0743
Epoch 8/100
552/552 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0139 - mae: 0.0567 - val_loss: 0.0182 - val_mae: 0.0788
Epoch 9/100
552/552 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/

In [17]:
prediction = model.predict(X_test[10100].reshape(1, -1))
print("Predicted outputs for test data:")
print("Acceleration:", prediction[0][0])
print("Braking:", prediction[0][1])
print("Clutch:", prediction[0][2])
print("Steering:", prediction[0][3])



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Predicted outputs for test data:
Acceleration: 0.026925564
Braking: 0.008691488
Clutch: 0.43290108
Steering: 0.03950654


In [16]:

print("Actual outputs for test data:")
print(y_test[10100])

Actual outputs for test data:
[0.         0.         0.47499999 0.2806612 ]


## Save the Model and Scaler

Now we'll save the trained model and the scaler so we can use them in the driver.py file. We'll use the newer Keras format for the model and joblib for the scaler.

In [18]:
import os
import joblib
from tensorflow.keras.models import load_model

# Create a models directory if it doesn't exist
model_dir = os.path.join(os.path.dirname(os.getcwd()), "models")
os.makedirs(model_dir, exist_ok=True)

# Save the model using the newer Keras format
model_path = os.path.join(model_dir, "torcs_driver_model.keras")
model.save(model_path)
print(f"Model saved to {model_path}")

# Save the model using the older HDF5 format
hdf5_model_path = os.path.join(model_dir, "torcs_driver_model.h5")
model.save(hdf5_model_path)
print(f"Model saved to {hdf5_model_path}")

# Save the scaler using joblib
scaler_path = os.path.join(model_dir, "torcs_scaler.joblib")
joblib.dump(scaler, scaler_path)
print(f"Scaler saved to {scaler_path}")

Model saved to c:\Users\Zestro\Desktop\AI\Project\TORCS-Using-NeuralNetworks\models\torcs_driver_model.keras
Model saved to c:\Users\Zestro\Desktop\AI\Project\TORCS-Using-NeuralNetworks\models\torcs_driver_model.h5
Scaler saved to c:\Users\Zestro\Desktop\AI\Project\TORCS-Using-NeuralNetworks\models\torcs_scaler.joblib


## Test Loading the Model and Scaler

Let's verify we can load the model and scaler correctly and get consistent predictions.

In [19]:
# Test loading the model and scaler
loaded_model = load_model(model_path)
loaded_scaler = joblib.load(scaler_path)

# Use the same sample_data as above

prediction_loaded = loaded_model.predict(X_test[10100].reshape(1,-1), verbose=0)

print("Prediction with loaded model:")
print("Acceleration:", prediction_loaded[0][0])
print("Braking:", prediction_loaded[0][1])
print("Steering:", prediction_loaded[0][2])


print("\nOriginal prediction:")
print("Acceleration:", prediction[0][0])
print("Braking:", prediction[0][1])
print("Steering:", prediction[0][2])


is_close = np.allclose(prediction_loaded, prediction, rtol=1e-5)
print(f"\nPredictions match: {is_close}")
if not is_close:
    print("\nDifference:")
    print(np.abs(prediction_loaded - prediction))

Prediction with loaded model:
Acceleration: 0.026925564
Braking: 0.008691488
Steering: 0.43290108

Original prediction:
Acceleration: 0.026925564
Braking: 0.008691488
Steering: 0.43290108

Predictions match: True


In [ ]:
import tensorflow as tf


hdf5_model_path = os.path.join(model_dir, "torcs_model_driver.h5")
old_model = tf.keras.models.load_model(hdf5_model_path)

converter = tf.lite.TFLiteConverter.from_keras_model(old_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

tflite_model_path = os.path.join(model_dir, "torcs_driver_model.tflite")
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)
print(f"TFLite model saved to {tflite_model_path}")


TypeError: pop expected at most 1 argument, got 2